import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";

// Primary font for body text - clean and highly readable
const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

// Secondary font for headings - modern and distinctive
const plusJakarta = Plus_Jakarta_Sans({
    subsets: ['latin'],
    variable: '--font-plus-jakarta',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${plusJakarta.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    )
}
